import mongoose, { Schema, Document } from 'mongoose';

// ============================================
// PROGRAM (PROGRAMA)
// Represents a generated course program/syllabus
// Can be generated by AI or manually created
// ============================================

export interface IProgram extends Document {
  clerkId: string;
  subjectId: string;
  subjectName: string;
  title: string;
  description: string;
  content: string; // JSON stringified program content
  source: 'ai' | 'manual';
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const ProgramSchema = new Schema<IProgram>({
  clerkId: { type: String, required: true, index: true },
  subjectId: { type: String, required: true },
  subjectName: { type: String, required: true },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  content: { type: String, required: true }, // Store as JSON string
  source: { type: String, enum: ['ai', 'manual'], default: 'manual' },
  isActive: { type: Boolean, default: true }
}, { timestamps: true });

// Index for queries
ProgramSchema.index({ clerkId: 1, subjectId: 1, isActive: 1 });

const Program = mongoose.models.Program || mongoose.model<IProgram>('Program', ProgramSchema);

export default Program;